version: "3.9"
networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
services:

  nginx:
    build:
      context: .
      dockerfile: dockerfile
    image: hydreon/timings
    
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-server.conf:/etc/nginx/nginx.conf
      - ./config.ini:/var/www/html/config.ini
      - ./php.ini:/etc/php8/php.ini
      - ./.htpasswd:/var/www/html/.htpasswd
      
      # - ./apache2.conf:/etc/apache2/apache2.conf
      

    
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"