version: "3.9"

services:
  timings:
    build:
      context: .
      dockerfile: dockerfile
    image: hydreon/timings
    ports:
      - 80:8080
    volumes:
      - ./nginx-server.conf:/etc/nginx/nginx.conf
      - ./config.ini:/var/www/html/config.ini